## Classification Algorithm

## Logistic Regression

## Objective: Predict Flower species based on sepal and petal length/width

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv("Iris.csv")

In [ ]:
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
data["Species"].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [ ]:
data.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
data.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [ ]:
X = data[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y = data["Species"]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr = LogisticRegression()

In [ ]:
lr.fit(X_train,y_train)

LogisticRegression()

In [ ]:
y_pred = lr.predict(X_test)

In [ ]:
lr.predict_proba(X_test)

array([[9.83262314e-01, 1.67376476e-02, 3.87012438e-08],
       [8.23836677e-02, 9.11718163e-01, 5.89816901e-03],
       [9.28686138e-05, 6.40359837e-02, 9.35871148e-01],
       [2.38528533e-05, 2.40684850e-02, 9.75907662e-01],
       [9.73001824e-01, 2.69981137e-02, 6.20749839e-08],
       [2.19958064e-06, 6.12103493e-03, 9.93876765e-01],
       [9.73235526e-01, 2.67643441e-02, 1.29558012e-07],
       [9.72292573e-01, 2.77073484e-02, 7.88500564e-08],
       [1.53536220e-06, 8.93158396e-03, 9.91066881e-01],
       [2.23710203e-02, 9.50872623e-01, 2.67563572e-02],
       [1.48615020e-03, 3.81619224e-01, 6.16894625e-01],
       [9.84550131e-01, 1.54498290e-02, 3.98707620e-08],
       [9.71931190e-01, 2.80687216e-02, 8.88672209e-08],
       [1.15685290e-02, 7.51070736e-01, 2.37360735e-01],
       [6.25802602e-03, 8.03754530e-01, 1.89987444e-01],
       [1.15389783e-04, 1.36740156e-01, 8.63144454e-01],
       [2.59189203e-02, 9.13806031e-01, 6.02750491e-02],
       [8.36304947e-04, 4.65680044e-01, 5.33483651e-01],
       [5.58241671e-02, 8.81189812e-01, 6.29860213e-02],
       [9.85403928e-01, 1.45960610e-02, 1.04974166e-08],
       [3.03134922e-01, 6.94529045e-01, 2.33603248e-03],
       [9.76695564e-01, 2.33044028e-02, 3.33525970e-08],
       [9.83788001e-01, 1.62119713e-02, 2.73638991e-08],
       [2.83112801e-03, 7.39407542e-01, 2.57761330e-01],
       [3.08540250e-03, 7.78720018e-01, 2.18194579e-01],
       [9.79692840e-01, 2.03071128e-02, 4.68974518e-08],
       [2.47132330e-05, 4.96616652e-02, 9.50313622e-01],
       [7.51421091e-03, 7.82411928e-01, 2.10073861e-01],
       [4.67237023e-04, 2.22277368e-01, 7.77255395e-01],
       [2.90893198e-05, 1.56427743e-01, 8.43543168e-01]])

In [ ]:
y_pred

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica'],
      dtype=object)

## Model Evaluation

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.91      0.95        11
 Iris-virginica       0.90      1.00      0.95         9

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30